### ISSUE TITLE
푼 문제 갱신 안됨

### ISSUE THREAD

**Issue by joonas-yoon** [alps-jbnu/litmus-site#19]
문제를 풀면 빨간색 (-) 모양에서 초록색 (v)이 되어야 하는데 갱신이 되지 않음

**Comment by joonas-yoon** [comment]
`supervisorctl reload` 를 해야되는걸로 보아 사이트는 문제는 아닌 거 같음.

서버 로그에서 이런 걸 발견함. 이것이 관련이 있을 거라 의심됨.
```
2018-01-17 16:10:06,591 INFO spawned: 'site' with pid 26868
2018-01-17 16:10:06,593 INFO spawned: 'bridged' with pid 26869
INFO 2018-01-17 16:10:07,679 23447 packet Opening connection to: [0.0.0.0]:9999
ERROR 2018-01-17 16:10:07,679 23447 packet Connection failed due to socket error: [0.0.0.0]:9999
Traceback (most recent call last):
  File "/home/litmus/judge/dmoj/packet.py", line 120, in _do_reconnect
    self._connect()
  File "/home/litmus/judge/dmoj/packet.py", line 84, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
WARNING 2018-01-17 16:10:07,680 23447 packet Attempting reconnection in 6s: [0.0.0.0]:9999
INFO 2018-01-17 16:10:07,680 23447 packet Dropping old connection.
2018-01-17 16:10:07,851 INFO success: site entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-17 16:10:07,851 INFO success: bridged entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO 2018-01-17 16:10:13,686 23447 packet Opening connection to: [0.0.0.0]:9999
INFO 2018-01-17 16:10:13,688 23447 packet Starting handshake with: [0.0.0.0]:9999
INFO 2018-01-17 16:10:13,691 23447 packet Awaiting handshake response: [0.0.0.0]:9999
INFO 2018-01-17 16:10:13,712 23447 packet Judge "litmus" online: [0.0.0.0]:9999
```

**Comment by joonas-yoon** [comment]
https://github.com/alps-jbnu/litmus-site/commit/a40ab9eb7ecd2d4d499482d9c1577433cb2d54cc
이슈 #30 와 함께 해결됨.
