### ISSUE TITLE
일부 문제 복제(clone) 오류

### ISSUE THREAD

**Issue by tuna1210** [alps-jbnu/litmus-site#38]
- [뉴비부터 망자까지](http://litmus.ga/problem/darksoul-3-goinmul) 
- [A* 알고리즘](http://litmus.ga/problem/a-star-algorithm)
복제시 오류 발생
```
SIGSEGV: invalid_state
corrupt page /problem/darksoul-3-goinmul/clone
site: fatal signal: Segmentation fault
site died (signal 500, exit -11)

panic: go back
Traceback (most recent call last):
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/litmus/site/judge/views/problem.py", line 627, in clone_problem
    problem.save()
  File "/home/litmus/site/judge/models/problem.py", line 286, in save
    super(Problem, self).save(*args, **kwargs)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/litmus/env/litmus/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
DataError: (1406, "Data too long for column 'code' at row 1")
```

**Comment by joonas-yoon** [comment]
`DataError: (1406, "Data too long for column 'code' at row 1")` 를 보면 code가 너무 길다고 함  

https://github.com/alps-jbnu/litmus-site/blob/04a89def0409d2148117256cdf51c8c1e8084e8c/judge/models/problem.py#L95-L98

여기를 보면 코드는 최대 길이가 20자로 제한되어 있습니다.
 Validator를 추가할 필요가 있어보임.

**Comment by joonas-yoon** [comment]
또는 복제할 때 길이를 조정하는 것도 좋을 것 같음
